lang_dict={

    'c#':'csharp',
'C#':'csharp',
'c#-2.0':'csharp',
'c#-3.0':'csharp',
'c#-4.0':'csharp',

'Go':'goLang',
'go':'goLang',

'VB':'VisualBasic',
'vb':'VisualBasic',
'Vb':'VisualBasic',
'VB.net':'VisualBasic',

'd3.js':'d3js',
'd3\.js':'d3js',
'nvd3.js':'d3js',

'g++5.1':'gplusplus',
'g++4.8':'gplusplus',
'g++':'gplusplus',
'gcc4.8':'gplusplus',
'gcc':'gplusplus',
'gcc10':'gplusplus',
'g++10':'gplusplus',

'c++':'cplusplus',
'C++':'cplusplus',
'c++14':'cplusplus',
'C++14':'cplusplus',
'c++17':'cplusplus',
'C++17':'cplusplus',
'c++98':'cplusplus',
'C++98':'cplusplus',
'c++11':'cplusplus',
'C++11':'cplusplus',
'c++20':'cplusplus', 

'clang++':'cplusplus',
'libstdc++':'cplusplus',
'libs++':'cplusplus',

##
'c++-cli':'cplusplus',
'c++-faq':'cplusplus',
'c++-tr2':'cplusplus',
'c++builder':'cplusplus',
##

'c':'clang',
'C':'clang',

'qt':'Qt_framework',
'qt4':'Qt_framework',
'qt5':'Qt_framework',
'qt-creator':'Qt_framework',
'pyqt':'Qt_framework',

'vue.js':'vuejs',
'vuejs2':'vuejs',
'vue-component':'vuejs',
'vuex':'vuejs',
'vuetify.js':'vuejs',
'vue-router':'vuejs',

'r':'rLang',
'R':'rLang',

'.net':'dotnet',
'.net-1.0' :'dotnet',
'.net-1.0':'dotnet',
'.net-1.1':'dotnet',
'.net-2.0':'dotnet',
'.net-3.0':'dotnet',
'.net-3.5':'dotnet',
'.net-4.0':'dotnet',
'.net-assembly':'dotnet',
'.net-attributes':'dotnet',
'.net-client-profile':'dotnet',
'.net-framework-version':'dotnet',

'io':'input_output',

'js':'javascript',

'vs':'VisualStudio',

##

'ansi-sql-92':'sql', 
'bpgsql':'sql', 
'dynamic-sql':'sql', 
'entity-sql':'sql', 
'linq-to-sql':'sql', 
'mysql':'sql', 
'mysql-error-1005':'sql', 
'mysql-error-1062':'sql', 
'mysql-error-1093':'sql', 
'mysql-error-1111':'sql', 
'mysql-error-1451':'sql', 
'mysql-error-2006':'sql', 
'mysql-management':'sql', 
'mysql-parameter':'sql', 
'mysql-workbench':'sql', 
'mysqldump':'sql', 
'mysqli':'sql', 
       
'nosql':'sql', 
'oracle-sqldeveloper':'sql', 
'plsql':'sql', 
'postgresql':'sql', 
'psql':'sql', 
'sql':'sql', 
'sql-convert':'sql', 
'sql-delete':'sql', 
'sql-execution-plan':'sql', 
'sql-injection':'sql', 
'sql-insert':'sql', 
'sql-like':'sql', 
'sql-loader':'sql', 
'sql-order-by':'sql', 
'sql-server':'sql', 
'sql-server-2000':'sql', 
'sql-server-2005':'sql', 
'sql-server-2005-express':'sql', 
'sql-server-2008':'sql', 
'sql-server-agent':'sql', 
'sql-server-ce':'sql', 
'sql-server-express':'sql', 
'sql-server-mobile':'sql', 
'sql-types':'sql', 
'sql-update':'sql', 
'sqlalchemy':'sql', 
'sqlclr':'sql', 
'sqlcommand':'sql', 
'sqlcompare':'sql', 
'sqlconnection':'sql', 
'sqldatatypes':'sql', 
'sqldmo':'sql', 
'sqlexception':'sql', 
'sqlite':'sql', 
'sqlncli':'sql', 
'sqlplus':'sql', 
'tsql':'sql', 
} 

program_dict ={
    'google-analytics':'google',
    'google-analytics-api':'google',
    'google-api':'google',
    'google-app-engine':'google',
    'google-authentication':'google',
    'google-calendar-api':'google',
    'google-checkout':'google',
    'google-chrome':'google',
    'google-chrome-devtools':'google',
    'google-cloud-datastore':'google',
    'google-code':'google',
    'google-custom-search':'google',
    'google-docs':'google',
    'google-maps':'google',
    'google-maps-api-2':'google',
    'google-maps-api-3':'google',
    'google-perftools':'google',
    'google-reader':'google',
    'google-search':'google',
    'google-sheets':'google',
    'google-toolbar':'google',
    'google-visualization':'google',
    'googlebot':'google',
    
    'amazon':'amazon',
    'amazon-ec2':'amazon',
    'amazon-s3':'amazon',
    'amazon-simpledb':'amazon',
    'amazon-web-services':'amazon',
    }
